### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by JLC7** [saraalemadi/DroneAudioDataset#1]
Thank you for the dataset! Do you have the model architectures you used available and plan to release them? Thanks

**Comment by saraalemadi** [comment]
Hi,

Thanks for reaching out. All the details about the model architectures used in this work can be found in my thesis here: [https://qspace.qu.edu.qa/handle/10576/17716](https://qspace.qu.edu.qa/handle/10576/17716).

Hope that helps.

-Sara A. Al-Emadi
